vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        club_photo:
            uri_prefix: /uploads/photo
            upload_destination: '%kernel.project_dir%/public/uploads/photo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
